# Generated by Django 4.1 on 2022-08-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMatias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('edad', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Hermana',
        ),
        migrations.DeleteModel(
            name='Hermano',
        ),
        migrations.DeleteModel(
            name='Madre',
        ),
        migrations.DeleteModel(
            name='Padre',
        ),
    ]
