# Generated by Django 4.1 on 2022-08-20 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMatias', '0002_familiar_delete_hermana_delete_hermano_delete_madre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2022, 8, 20, 16, 55, 39, 108079, tzinfo=datetime.timezone.utc), verbose_name=datetime.datetime),
            preserve_default=False,
        ),
    ]
